name: face_recognition_brain
on:
  push:
    branches: [main, staging, dev, feature/*, bug/*]
  pull_request:
    branches: [feature/*, bug/* ]
env:
  buildNumber: $(date +'%Y%m%d')-${{ github.run_number }}
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x, 16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version }}
      - name: NPM Install
        run: npm ci
      - name: NPM Test
        run: npm test