name: Add and Label Issues
on:
  issues:
    types:
      - opened
env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issues
        uses: andymckay/labeler@5c59dabdfd4dd5bd9c6e6d255b01b9d764af4414
        with:
          add-labels: "frontend"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  add_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Assign to One Project
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: github.event.action == 'opened'
        with:
          project: https://github.com/users/TheFlyer1983/projects/1
          column_name: "Backlog"
