name: Monthly Maintenance Audit
on:
  schedule:
    - cron: "0 2 1 * *"

jobs:
  create_issue:
    name: Create Monthly Maintenance Audit Issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%m-%Y')"
      - name: Create Monthly Maintenance Audit Issue
        uses: imjohnbo/issue-bot@v3.3.4
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          labels: "maintenance, audit"
          title: Maintenance & Dependancy Update - ${{ steps.date.outputs.date }}
          body: |
            ### Update Outdated Packages and Dependancies

            #### Acceptance Criteria

            - Update any outdated packages
            - Audit current packages for vulnerabilities
            - Update any dependancies with vulnerabilities (where possible)
          pinned: true
          close-previous: true
